#site settings
title: Wavelet coherence
email: ag+wtc@glaciology.net
description: A matlab toolbox for cross-wavelet and wavelet coherence analysis
baseurl: /wavelet-coherence
url: http://grinsted.github.io
twitter_username: agrinsted
github_username: grinsted
permalink: /:categories/:title/
theme: jekyll-theme-dinky